# Generated by Django 4.2.7 on 2023-11-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_instruction_step_recipe_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='visibility',
        ),
        migrations.AddField(
            model_name='recipe',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('DRAFT', 'DRAFT')], default=('PUBLIC', 'PUBLIC'), max_length=7),
        ),
    ]
