# Generated by Django 4.2.7 on 2023-11-26 23:30

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_images_imagerecipe_likerecipe_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.upload_image),
        ),
        migrations.DeleteModel(
            name='ImageRecipe',
        ),
    ]
