# Generated by Django 4.2.7 on 2023-11-27 06:03

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_image_delete_imagerecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.upload_image),
        ),
    ]
