# Generated by Django 4.2.7 on 2023-11-27 06:13

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_step_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.upload_step),
        ),
        migrations.AlterField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe'),
        ),
    ]
